# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a7bfae9a8a3ade8f65e614631e871e2c941007fd80749187d3a45b8e2488f8b685f03c0a3936c934f17d517b04698d3cfc1507b35517f28248ba6907b380fd4e
  auth_secret_key: 844e71a792781193c7234c7c18be8692c7b560ffa5063cb844d6737e4dc6487ccaee044b3973ba9e89de538706df7c9b510335cf5bb17eee3eeccd26ca9d70d6

test:
  secret_key_base: ca1437c5984f4746e57d79eb7d9ea786b07f36aaa2f444fe4c7630282b21fe5e903e5af2f5d29ee03d73ddbbc9b75218c469d25156c7c59fe36ec38b6d24e16f
  auth_secret_key: 3193e4fe0106f0951161e8050883c267da9527af01a6ea8cb961c1a38ec66871acc3d5863fecec0d96c9219248a96ef2deffa7a92441092ba5d5c83671a8eebf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth_secret_key: <%= ENV["AUTH_SECRET_KEY"] %>
